### ISSUE TITLE
Option to suppress POST and GET calls in stdout

### ISSUE THREAD

**Issue by adamwinn** [crazy-max/docker-rtorrent-rutorrent#121]
Can we get an option to suppress the POST and GET http calls?

![Screen Shot 2021-09-04 at 1 19 18 AM](https://user-images.githubusercontent.com/3028964/132086389-b5fe5767-6b24-4184-8f0f-c5aa4eee4c3e.jpg)

```
172.17.0.1 - - [04/Sep/2021:01:11:35 -0600] "POST /plugins/httprpc/action.php HTTP/1.1" 200 122 "http://diskstation.local:9085/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4613.0 Safari/537.36 Edg/95.0.997.1"
```

**Comment by Dorno** [comment]
This would be very welcome as I am seeing something like 17k entries in the log for the first day I installed rTorrent-ruTorrent.
In just 3 hours today I have over 6k log entries. I guess that means I'll see about 48k for a full day? It'd be really nice if there was a way to avoid these since Synology doesn't offer an easy way to empty the log other than removing and reinstalling the client, which is obviously not ideal.
