### ISSUE TITLE
Torrents being added in pausing state (help)

### ISSUE THREAD

**Issue by Aks491** [crazy-max/docker-rtorrent-rutorrent#31]
All the torrents are being added in pausing state. What am i doing wrong ? (help)

**Comment by crazy-max** [comment]
@Aks491 [Support directly related to rTorrent or ruTorrent will not be provided if your problem is not related to the operation of this image](Support directly related to rTorrent or ruTorrent will not be provided if your problem is not related to the operation of this image.). For help about your issue see https://github.com/Novik/ruTorrent/search?q=pause+state&type=Issues

**Comment by Aks491** [comment]
Keeping the erasedata plugin solved it.

**Comment by mabushey** [comment]
Actually this container is the issue, as the linuxserver container does not have this issue.

**Comment by blasterspike** [comment]
I have been having a similar issue, where all magnet links go in Pause state after few seconds.
With using torrent files I don't have any issue.
This wasn't happening before with the [linuxserver](https://github.com/linuxserver/docker-rutorrent) image I was using before.
After comparing the _rtorrent.rc_ files, I have found that the problem is caused by the last line of _/data/rtorrent/.rtorrent.rc_
```
method.set_key = event.download.erased,delete_erased,"execute=/replace/me/path/to/script.sh,$d.base_path="
```
This is the open issue for rtorrent: https://github.com/rakshasa/rtorrent/issues/1053
So for the moment I have commented the line to make it working with magnet links.

**Comment by rpgdev** [comment]
> Keeping the erasedata plugin solved it.

What do you mean? @Aks491

**Comment by rpgdev** [comment]
> So for the moment I have commented the line to make it working with magnet links.

You lose the ability to delete the files associated with a torrent and it happens silently, no warning from rutorrent. Sounds like a good way to wast a bunch of your available space. Not a viable workaround imho.

**Comment by mabushey** [comment]
@blasterspike Thank you that's awesome! Sounds like an extremely viable workaround imho, I can delete from the File System perfectly fine.

**Comment by rpgdev** [comment]
@mabushey you mean you manually delete from the file system, correct? For me commenting out that line stopped rutorrent from deleting the files.
