### ISSUE TITLE
Move on complete escaping slash

### ISSUE THREAD

**Issue by Sveeeeeen** [crazy-max/docker-rtorrent-rutorrent#43]
Hello,

I am facing the issue that moving after download finished is escaping the slash inside my path.
For example, I am downloading using this dir "temp/MOVIES/TV". Download in the tmp dir is fine. After he finished the download he is moving it to "complete/MOVIES%2FTV".

Any ideas what could be the issue here?

I am using the default config for moving finished torrents.
```
# Move finished (no need Autotools/Automove plugin on ruTorrent)
method.insert = d.get_finished_dir, simple, "cat=$cfg.download_complete=,$d.custom1="
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="
```

**Comment by crazy-max** [comment]
@Sveeeeeen Looks like you already have your response: rakshasa/rtorrent#1050 (issue with ruTorrent)

**Comment by topjes** [comment]
Hi,

I had the same problem with "%2F" instead of subfolders. And I solved the problem.

I get out of the "autotools section" in rtorrent.rc completely
So I commented with "#" all these lines

<code># method.insert = ...</code>
<code># method.insert = ...</code>
<code># method.insert = ...</code>
<code># method.set_key = ...</code>

Then I used the rutorrent GUI Autotools plugin. And I configured there the watch directory and all the rest.

And NO MORE "%2F". Now everything works properly. Files are moved to proper subdirectories.
