### ISSUE TITLE
Healthcheck always state unhealthy

### ISSUE THREAD

**Issue by lilws** [crazy-max/docker-rtorrent-rutorrent#68]
I run docker ps and find out that healtcheck always state unhealthy. Is it ok for this happen?

**Comment by XxAcielxX** [comment]
I didn't like it either, that's why I removed it in my image.

**Comment by crazy-max** [comment]
@lilws 

> I run docker ps and find out that healtcheck always state unhealthy. Is it ok for this happen?

No, it shouldn't, but I guess it's because you [changed this image](https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/65#issuecomment-808844773). Execute the [healthcheck script](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/rootfs/usr/local/bin/healthcheck) inside the container to known why:

```shell
curl -Ssd "<?xml version='1.0'?><methodCall><methodName>system.api_version</methodName></methodCall>" http://127.0.0.1:8001
curl -Ss http://127.0.0.1:8081/ping
curl -Ss http://127.0.0.1:9001
```

**Comment by lilws** [comment]
@crazy-max Thanks, I've just created another temporary container and both of them return healthy, so I removed the temporary and the main container return healthy even after a restart too.

**Comment by lilws** [comment]
Anyway, healthcheck failed at WebDAV.

**Comment by XxAcielxX** [comment]
> Anyway, healthcheck failed at WebDAV.

You have changed default downloads location, but I think you haven't updated it in `/tpls/etc/nginx/conf.d/webdav.conf`, line 5 & 23.

**Comment by lilws** [comment]
Yeah. I did that already so WebDAV healthcheck is good now.
